### PR TITLE
#19 Add Dockerfile.

### PR DESCRIPTION
**Pull request by stephenwithav**
Include ca-certificates.crt to allow secure connections to the outside
world.

Future backends may require this.

### CODE REVIEW

**Comment by vimukthi-git** [comment]
@stephenwithav Although you have permissions, do not merge until a reviewer(me in this case) approves. I will do the same. I was still reviewing this as I want to make sure that we have the right build process for images.

**Comment by stephenwithav** [comment]
Apologies, @vimukthi-git--I will do so in the future.

Aside from a force push, is there any way to unmerge this PR?

**Comment by stephenwithav** [comment]
https://help.github.com/articles/reverting-a-pull-request/

**Comment by vimukthi-git** [comment]
@stephenwithav no need to do so for this one, we can follow review process from now on. Having a docker image is still good.

**Pull request merged**
